highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-org-to-html
title: DemonKingSwarn's Blog
description: Welcome to my weblog
author: DemonKingSwarn
permalink: /:year/:month/:day/:title:output_ext
